name: release

on:
  release:
    types: [ published ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Build
        run: |
          cd node-proxy
          npm install && npm run build
      - name: Compress
        if: ${{ success() }}
        run: |
          cd node-proxy/build
          ls -1 | xargs -I {} zip {}.zip {} && \
            ls -1 *.zip | xargs -I {} shasum -a 256 {} >> sha256.txt
      - name: Upload assets
        if: ${{ success() }}
        uses: softprops/action-gh-release@v2
        with:
          files: |
            node-proxy/build/*.zip
            node-proxy/build/sha256.txt
          prerelease: false
